"""empty message

Revision ID: 0ed154907d83
Revises: a01a420d4f33
Create Date: 2018-12-23 16:17:41.742777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed154907d83'
down_revision = 'a01a420d4f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
